var showdown  = require('showdown');
var request = require('request');

var converter = new showdown.Converter({
  ghCompatibleHeaderId: true,
  ghMentions: true,
});

converter.setFlavor('github');

exports.parse = function(user, name, callback)
{
  //https://github.com/kfricilone/taylir
  //https://raw.githubusercontent.com/kfricilone/taylir/master/README.md

  var url = 'https://github.com/' + user + '/' + name;
  var rmUrl = 'https://raw.githubusercontent.com/' + user + '/' + name + '/master/README.md';

  request(rmUrl, function(err, resp, body)
  {

    request(url, function(error, response, descBody)
    {
      var regex = /<span class="text-gray-dark mr-2" itemprop="about">[\n \t]*[a-zA-Z0-9 _\-.]*[\n \t]*<\/span>/
      var description = ``;

      var result = regex.exec(descBody);
      if (result !== null)
      {
        description = result[0].replace('<span class="text-gray-dark mr-2" itemprop="about">', '').replace('<\/span>', '').trim();
      }

      let preContent = `
      <!DOCTYPE html>
      <html lang="en-US">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <meta name="theme-color" content="#157878">
          <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
          <link rel="stylesheet" href="/css/style.css">
        </head>

        <body>
          <a id="skip-to-content" href="#content">Skip to the content.</a>

          <header class="page-header" role="banner">
            <h1 class="project-name">` + name + `</h1>
            <h2 class="project-tagline">` + description + `</h2>
              <a href="` + url + `" class="btn">View on GitHub</a>
              <a href="` + url + `/zipball/master" class="btn">Download .zip</a>
              <a href="` + url + `/tarball/master" class="btn">Download .tar.gz</a>
          </header>

          <main id="content" class="main-content" role="main">
            <div class="border">
        `;

      let postContent = `
            </div>
            <footer class="site-footer">
              <span class="site-footer-owner"><a href="https://github.com/pages-themes/cayman">cayman</a> is maintained by <a href="https://github.com/pages-themes">pages-themes</a>.</span>
              <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span>
            </footer>
          </main>
        </body>
      </html>`;

      var html = converter.makeHtml(body);
      /*if (body.startsWith('['))
      {
        html = html.replace('<p>', '<p align="center"><br />');
      }*/

      regex = /\/><br \/>/g;
      html = html.replace(regex, '/>');

      regex = /a><br \/>/g;
      html = html.replace(regex, 'a>');

      callback(preContent + html + postContent);
    });
  });
}
